
plink.path <- bigsnpr::download_plink2()

# set the path to plink
set_plink_path(plink.path)

# set a prefix for outputs generated by this run 
set_panvar_prefix("PanvarExample")

# set a directory to output results and intermediate files
current.directory <- tempdir()
set_out_dir(current.directory)

genotype.path <- system.file("extdata", 
                             "Setaria_shattering_example_pruned.bed",
                             package = "panvaR")

phenotype.path <- system.file("extdata",
                              "Setaria_shattering_example_phenotype.tsv",
                              package = "panvaR")

make_panvar_inputs(genotype.path = genotype.path,
                   phenotype.path = phenotype.path)

filtered.bedfile.fullpath <- list.files(options()$panvar_outdir,
                                        pattern = "bed$",
                                        full.names = TRUE)

plot_pc_scree(bedfile.path = filtered.bedfile.fullpath, num.pcs = 10)

panvar_mvp_gwas(inputs.dir = options()$panvar_outdir,
                npcs = 2,
                gwas.model = "GLM",
                output.manhattan = T)

filtered.bedfile <- list.files(options()$panvar_outdir, pattern = "bed$")

out_ld <-
  get_ld_in_window(
    tag.snp = "Chr_05-6857045",
    window = 500,
    geno.bed = filtered.bedfile,
    in.dir = current.directory
  )
head(out_ld$table)

annotation.table <- read.csv(system.file("extdata",
                                         "Setaria_shattering_annotation.csv",
                                         package = "panvaR"))

head(annotation.table)

gwas.path <- list.files(options()$panvar_outdir,
                                        pattern = "GWASresults\\.csv$",
                                        full.names = TRUE)

# match chromosome format, want to use numeric style chromsome, see note below
head(annotation.table$CHR)
gwas.df <- read.csv(gwas.path) 
head(gwas.df$CHR)
gwas.df <- gwas.df %>% 
  mutate(CHR = panvaR::get_chrom_from_id(marker.ID, sep = "-"))
head(gwas.df$CHR)

# make the tables 
my.tag.snp <- "Chr_05-6843742"
old.tag.snp <- "Chr_05-6857045"

tables <- make_panvar_tables(gwas.res = gwas.df,
                             tag.snp = my.tag.snp,
                             # qtl.df = qtl.df.test,
                             annotation.table = annotation.table,
                             plink.path = options()$plink_path,
                             pvals.in.log = F,
                             geno.bed.filename = filtered.bedfile,
                             geno.bed.directory = current.directory,
                             window = 250,
                             compute.scores = T,
                             snp.to.gene.vars = c("LD", "snp.score"),
                             snp.to.gene.buffer = 5)

names(tables)
head(tables$gwas)
head(tables$anno)

# the snp id'd by the paper is the second ranked pvalue in my gwas results
# therefore the top snp looks like it doesn't quite line up because everything is centered around the "key-snp"
tables$key.snp
head(tables$gwas)
temp <- gwas.df %>% 
  arrange(desc(LOGPVAL)) %>% 
  mutate(is.key = marker.ID == tables$key.snp)

p <-
plot_panvar(panvar.table.list = tables,
            pvals.in.log = F,
            plot.r2.thresh = .2,
            unplotted.alpha = .4,
            window = 75,
            sig.line = 6,
            orient = "H",
            qualitative.annotation = NULL,
            qualitative.shape.scale = NULL,
            quantitative.annotation = NULL,
            quantitative.fill.scale = NULL,
            include.gene.id = T,
            annotation.point.variable = "snp.score",
            plot.effect = F
)

ggsave("PanvarExamplePlot.png",
       plot = p,
       height = 10,
       width = 15,
       bg = "white",
       units = "in",
       dpi = "retina")
