#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom bigstatsr big_univLinReg
#' @importFrom dplyr all_of
#' @importFrom dplyr dense_rank
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr group_by
#' @importFrom dplyr left_join
#' @importFrom dplyr n
#' @importFrom dplyr rename
#' @importFrom dplyr slice
#' @importFrom dplyr starts_with
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 binned_scale
#' @importFrom ggplot2 coord_cartesian
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_rug
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_alpha
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_shape_manual
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_x_reverse
#' @importFrom ggplot2 scale_y_reverse
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme_void
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 ylim
#' @importFrom khroma plot_scheme
#' @importFrom rlang .data
#' @importFrom rMVP attach.big.matrix
#' @importFrom rMVP MVP
#' @importFrom rMVP MVP.Data
#' @importFrom stats complete.cases
#' @importFrom stats cor.test
#' @importFrom stats predict
#' @importFrom stringr str_detect
#' @importFrom stringr str_replace
#' @importFrom tibble enframe
#' @importFrom tidyr unnest_longer
#' @importFrom utils read.delim
#' @importFrom utils read.table
#' @importFrom utils setTxtProgressBar
#' @importFrom utils txtProgressBar
#' @importFrom utils write.csv
#' @importFrom utils write.table
## usethis namespace: end
NULL
