#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom bigsnpr download_plink2
#' @importFrom bigstatsr big_univLinReg
#' @importFrom bslib tooltip
#' @importFrom data.table fread
#' @importFrom dplyr %>%
#' @importFrom dplyr across
#' @importFrom dplyr add_row
#' @importFrom dplyr all_of
#' @importFrom dplyr arrange
#' @importFrom dplyr between
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr contains
#' @importFrom dplyr dense_rank
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr last_col
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr starts_with
#' @importFrom dplyr summarize
#' @importFrom dplyr ungroup
#' @importFrom ggfittext geom_fit_text
#' @importFrom gggenes geom_gene_arrow
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 binned_scale
#' @importFrom ggplot2 coord_cartesian
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_rug
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_alpha
#' @importFrom ggplot2 scale_alpha_continuous
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_color_viridis_b
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_fill_viridis_b
#' @importFrom ggplot2 scale_shape_manual
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_x_reverse
#' @importFrom ggplot2 scale_y_reverse
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme_void
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylim
#' @importFrom khroma plot_scheme
#' @importFrom patchwork plot_layout
#' @importFrom pcadapt pcadapt
#' @importFrom pcadapt read.pcadapt
#' @importFrom rlang .data
#' @importFrom rMVP attach.big.matrix
#' @importFrom rMVP MVP
#' @importFrom rMVP MVP.Data
#' @importFrom stats complete.cases
#' @importFrom stats cor.test
#' @importFrom stats median
#' @importFrom stats predict
#' @importFrom stats weighted.mean
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract_all
#' @importFrom stringr str_replace
#' @importFrom sys exec_wait
#' @importFrom tibble add_column
#' @importFrom tibble enframe
#' @importFrom tidyr unnest_longer
#' @importFrom utils capture.output
#' @importFrom utils read.delim
#' @importFrom utils read.table
#' @importFrom utils setTxtProgressBar
#' @importFrom utils txtProgressBar
#' @importFrom utils write.csv
#' @importFrom utils write.table
## usethis namespace: end
NULL
